# Generated by Django 4.2.5 on 2023-10-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Otp',
        ),
    ]
