# Generated by Django 4.2.5 on 2023-10-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_rename_order_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
